---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc
spec:
  replicas: 1
  template:
    metadata:
      name: svc
    spec:
      serviceAccountName: svc
      containers:
        - name: svc
          image: gcr.io/spiffe-io/spire-agent:1.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///spire-agent-socket/agent.sock
          command:
            - sleep
          args:
            - "1000000000"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /spire-agent-socket
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
