apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: vault
  app.kubernetes.io/version: 1.8.3
  app.kubernetes.io/component: ca
  app.kubernetes.io/part-of: vault
namespace: vault
resources:
  - self-signed-cluster-issuer.yaml
  - vault-issuer.yaml
  - vault-ca-certificate.yaml
  - vault-certificate.yaml
