---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-ca
  namespace: vault
spec:
  issuerRef:
    name: self-signed-root
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: self-signed-ca
  secretName: vault-ca
