apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: svc-b
  app.kubernetes.io/version: 1.0.2
  app.kubernetes.io/component: workload
  app.kubernetes.io/part-of: spire
nameSuffix: -b
resources:
  - ../../base/svc
