---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-copy-volume-mounts: spire-agent
        vault.hashicorp.com/agent-pre-populate: "false"
        vault.hashicorp.com/agent-configmap: vault-agent
    spec:
      initContainers:
        - name: init
          image: gcr.io/spiffe-io/wait-for-it
          args:
            - -t
            - "30"
            - spire-server:8081
      containers:
        - name: spire-agent
          volumeMounts:
            - mountPath: /var/run/secrets/tokens
              name: vault-token
      volumes:
        - name: vault-token
          projected:
            sources:
              - serviceAccountToken:
                  path: vault-token
                  audience: vault
                  expirationSeconds: 900
