apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: spire-agent
  app.kubernetes.io/version: 1.0.2
  app.kubernetes.io/component: agent
  app.kubernetes.io/part-of: spire
namespace: spire
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: spire-agent
    files:
      - agent.hcl
patchesStrategicMerge:
  - daemonset-patch.yaml
resources:
  - ../../base/agent
