---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: spire-server
          image: spire-server:latest-local
          imagePullPolicy: Never
