apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: spire-server
  app.kubernetes.io/version: latest-local
  app.kubernetes.io/component: server
  app.kubernetes.io/part-of: spire
namespace: spire
patchesStrategicMerge:
  - deployment-patch.yaml
resources:
  - ../server
