---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-server
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: ca
          image: curlimages/curl
          command:
            - sh
          args:
            - -c
            - curl -k https://vault.vault.svc:8200/v1/spiffe/ca/pem -o /run/secrets/ca/ca.pem
          volumeMounts:
            - mountPath: /run/secrets/ca
              name: ca-crt
      containers:
        - name: spire-server
          volumeMounts:
            - mountPath: /var/run/secrets/tokens
              name: vault-token
            - mountPath: /run/secrets/ca
              name: ca-crt
              readOnly: true
      volumes:
        - name: vault-token
          projected:
            sources:
              - serviceAccountToken:
                  path: vault-token
                  audience: vault
                  expirationSeconds: 900
        - name: ca-crt
          emptyDir:
            medium: Memory
