apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: spire-server
  app.kubernetes.io/version: 1.0.2
  app.kubernetes.io/component: server
  app.kubernetes.io/part-of: spire
namespace: spire
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: spire-server
    files:
      - server.hcl
patchesStrategicMerge:
  - deployment-patch.yaml
resources:
  - ../../base/server
