apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: spire-agent
  app.kubernetes.io/version: 1.1.0
  app.kubernetes.io/component: agent
  app.kubernetes.io/part-of: spire
namespace: spire
resources:
  - csi-driver.yaml
  - sa.yaml
  - rbac.yaml
  - daemonset.yaml
